image: node:16

stages:
  - build
  - deploy


build_dev:
  except:
    - main
  stage: build
  variables:
    NX_API_KEY: ${NX_API_KEY}
    NX_AUTH_DOMAIN: ${NX_AUTH_DOMAIN}
    NX_PROJECT_ID: ${NX_PROJECT_ID}
    NX_STORAGE_BUCKET: ${NX_STORAGE_BUCKET}
    NX_MESSAGING_SENDER_ID: ${NX_MESSAGING_SENDER_ID}
    NX_APP_ID: ${NX_MESSAGING_SENDER_ID}
  before_script:
    - npm ci --cache .npm --prefer-offline --force
  script:
    - npm run run:many
  environment:
    name: 'Development'
  artifacts:
    expire_in: '300'
    paths:
      - dist

deploy_dev:
  only:
    - development
  except:
    - master
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline --force
    - npm i -g firebase-tools
  script:
    - npm run run:many
    - firebase deploy --only hosting:muiapp --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:antapp --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:primeapp --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:semanticapp --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:tailwindapp --token $FIREBASE_TOKEN
  environment:
    name: 'Development'
